decky-linux: auto-create a vm if needed, clean up

diff --git a/decky-linux b/decky-linux
--- a/decky-linux
+++ b/decky-linux
@@ -48,10 +48,15 @@ run() {
 
 verbose=1
 
-if ! limactl list --quiet docker &>/dev/null || limactl list --all-fields docker | tail -n +2 | awk '{print $2}' | grep -q Stopped; then
-    PATH="$HOME/Projects/lima/lima-0.17.2-Darwin-x86_64/bin:$PATH"
-    run limactl start docker || die "failed to start docker VM"
-    trap 'run limactl stop docker' EXIT INT TERM
+LIMA_DOCKER_INSTANCE=${LIMA_DOCKER_INSTANCE:-docker}
+
+if ! limactl list --quiet "$LIMA_DOCKER_INSTANCE" &>/dev/null; then
+    run limactl create --name="$LIMA_DOCKER_INSTANCE" "$HOME/Projects/lima/$LIMA_DOCKER_INSTANCE.yaml"
+    run limactl start "$LIMA_DOCKER_INSTANCE" || die "failed to start $LIMA_DOCKER_INSTANCE VM"
+    trap 'run limactl stop -f "$LIMA_DOCKER_INSTANCE"' EXIT INT TERM
+elif limactl list --all-fields "$LIMA_DOCKER_INSTANCE" | tail -n +2 | awk '{print $2}' | grep -q Stopped; then
+    run limactl start "$LIMA_DOCKER_INSTANCE" || die "failed to start $LIMA_DOCKER_INSTANCE VM"
+    trap 'run limactl stop -f "$LIMA_DOCKER_INSTANCE"' EXIT INT TERM
 fi
 
 binary="${XDG_DATA_HOME:-$HOME/.local}/bin/decky-linux-binary"
@@ -60,22 +65,28 @@ if ! [ -x "$binary" ]; then
     curl -fsSL --output "$binary" https://github.com/SteamDeckHomebrew/cli/releases/download/0.0.4/decky-linux-x86_64
     chmod +x "$binary"
 fi
-
-if [ -d .git ]; then
-    run git clean -qfdx || msg "warning: git clean failed, continuing"
-fi
 if [ "${1:-}" = "plugin" ] && [ "${2:-}" = "build" ]; then
     shift 2
+    if [ -d .git ]; then
+        run git clean -fqdx -e ./out/ || msg "warning: git clean failed, continuing"
+    fi
+    if [ -d tmp ]; then
+        if command -v trash &>/dev/null; then
+            run trash tmp || msg "warning: trash tmp failed, continuing"
+        else
+            run rm -rf tmp || msg "warning: rm -rf tmp failed, continuing"
+        fi
+    fi
     mkdir -p tmp
     set -- plugin build --build-as-root --tmp-output-path "$PWD/tmp" --output-path ./out "$@"
 fi
-run limactl shell docker "$binary" "$@"
-run git clean -fqdx -e ./out/
+run limactl shell "$LIMA_DOCKER_INSTANCE" "$binary" "$@"
+run git clean -fqdx -e /out/
 if [ "${1:-}" = "plugin" ] && [ "${2:-}" = "build" ] && [ -d ./out ]; then
     output=$(find ./out -mindepth 1 -maxdepth 1 -type f | head -n 1)
     if [ -n "$output" ]; then
         msg "Decky build complete: %s" "$output"
     else
-        die "Error: Decky build complete, but nothing found in %s/out/" "$builddir"
+        die "Error: Decky build complete, but nothing found in ./out/"
     fi
 fi
